/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/banana-v1.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/banana-v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.banana_low_Banana_0.geometry} material={materials.Banana} rotation={[0, 0.15, -0.01]} />
      </group>
    </group>
  )
}

useGLTF.preload('/banana-v1-transformed.glb')
